# Generated by Django 5.0.1 on 2024-02-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='parent_question',
        ),
    ]
